// <auto-generated />
using System;
using BOMA.WRT.Infrastructure.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BOMA.WRT.Infrastructure.Database.Migrations
{
    [DbContext(typeof(BomaDbContext))]
    [Migration("20220624054832_InitialWorkingTimeRecordsTable")]
    partial class InitialWorkingTimeRecordsTable
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("BOMA.WTR.Domain.Entities.WorkingTimeRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<byte>("EventType")
                        .HasColumnType("tinyint")
                        .HasColumnName("EventType");

                    b.Property<int>("GroupId")
                        .HasColumnType("int")
                        .HasColumnName("GroupId");

                    b.Property<DateTime>("OccuredAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("OccuredAt");

                    b.Property<int>("UserRcpId")
                        .HasColumnType("int")
                        .HasColumnName("UserRcpId");

                    b.HasKey("Id");

                    b.ToTable("WorkingTimeRecords", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
