// <auto-generated />
using System;
using BOMA.WTR.Infrastructure.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BOMA.WTR.Infrastructure.Database.Migrations
{
    [DbContext(typeof(BomaDbContext))]
    [Migration("20220713093522_AddInitialDepartmentsData")]
    partial class AddInitialDepartmentsData
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("BOMA.WTR.Domain.AggregateModels.Employee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("DepartmentId")
                        .HasColumnType("int");

                    b.Property<int>("RcpId")
                        .HasColumnType("int")
                        .HasColumnName("RcpId");

                    b.HasKey("Id");

                    b.HasIndex("DepartmentId");

                    b.ToTable("Employees", (string)null);
                });

            modelBuilder.Entity("BOMA.WTR.Domain.AggregateModels.Entities.Department", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.HasKey("Id");

                    b.ToTable("Departments", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Magazyn"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Akcesoria"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Produkcja"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Pakowanie"
                        },
                        new
                        {
                            Id = 5,
                            Name = ""
                        },
                        new
                        {
                            Id = 6,
                            Name = "BOMA"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Zlecenia"
                        },
                        new
                        {
                            Id = 8,
                            Name = "Agencja"
                        });
                });

            modelBuilder.Entity("BOMA.WTR.Domain.AggregateModels.Entities.WorkingTimeRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("DepartmentId")
                        .HasColumnType("int")
                        .HasColumnName("DepartmentId");

                    b.Property<byte>("EventType")
                        .HasColumnType("tinyint")
                        .HasColumnName("EventType");

                    b.Property<DateTime>("OccuredAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("OccuredAt");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DepartmentId");

                    b.HasIndex("UserId");

                    b.ToTable("WorkingTimeRecords", (string)null);
                });

            modelBuilder.Entity("BOMA.WTR.Domain.AggregateModels.Entities.WorkingTimeRecordAggregatedHistory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<decimal>("BaseNormativeHours")
                        .HasColumnType("decimal(10,2)");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("FiftyPercentageBonusHours")
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal>("HundredPercentageBonusHours")
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal>("NightHours")
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal>("SaturdayHours")
                        .HasColumnType("decimal(10,2)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<decimal>("WorkedHoursRounded")
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal>("WorkedMinutes")
                        .HasColumnType("decimal(10,2)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("WorkingTimeRecordAggregatedHistories", (string)null);
                });

            modelBuilder.Entity("BOMA.WTR.Domain.AggregateModels.Employee", b =>
                {
                    b.HasOne("BOMA.WTR.Domain.AggregateModels.Entities.Department", "Department")
                        .WithMany()
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("BOMA.WTR.Domain.AggregateModels.ValueObjects.Money", "Salary", b1 =>
                        {
                            b1.Property<int>("EmployeeId")
                                .HasColumnType("int");

                            b1.Property<decimal>("Amount")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("money")
                                .HasDefaultValue(0m)
                                .HasColumnName("BaseSalaryAmount");

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .ValueGeneratedOnAdd()
                                .HasColumnType("nvarchar(max)")
                                .HasDefaultValue("PLN")
                                .HasColumnName("Currency");

                            b1.HasKey("EmployeeId");

                            b1.ToTable("Employees");

                            b1.WithOwner()
                                .HasForeignKey("EmployeeId");
                        });

                    b.OwnsOne("BOMA.WTR.Domain.AggregateModels.ValueObjects.Name", "Name", b1 =>
                        {
                            b1.Property<int>("EmployeeId")
                                .HasColumnType("int");

                            b1.Property<string>("FirstName")
                                .IsRequired()
                                .HasMaxLength(64)
                                .HasColumnType("nvarchar(64)")
                                .HasColumnName("FirstName");

                            b1.Property<string>("LastName")
                                .IsRequired()
                                .HasMaxLength(64)
                                .HasColumnType("nvarchar(64)")
                                .HasColumnName("LastName");

                            b1.HasKey("EmployeeId");

                            b1.ToTable("Employees");

                            b1.WithOwner()
                                .HasForeignKey("EmployeeId");
                        });

                    b.OwnsOne("BOMA.WTR.Domain.AggregateModels.ValueObjects.PercentageBonus", "SalaryBonusPercentage", b1 =>
                        {
                            b1.Property<int>("EmployeeId")
                                .HasColumnType("int");

                            b1.Property<decimal>("Value")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("money")
                                .HasDefaultValue(0m)
                                .HasColumnName("PercentageBonusSalary");

                            b1.HasKey("EmployeeId");

                            b1.ToTable("Employees");

                            b1.WithOwner()
                                .HasForeignKey("EmployeeId");
                        });

                    b.Navigation("Department");

                    b.Navigation("Name")
                        .IsRequired();

                    b.Navigation("Salary")
                        .IsRequired();

                    b.Navigation("SalaryBonusPercentage")
                        .IsRequired();
                });

            modelBuilder.Entity("BOMA.WTR.Domain.AggregateModels.Entities.WorkingTimeRecord", b =>
                {
                    b.HasOne("BOMA.WTR.Domain.AggregateModels.Entities.Department", "Department")
                        .WithMany()
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("BOMA.WTR.Domain.AggregateModels.Employee", null)
                        .WithMany("WorkingTimeRecords")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Department");
                });

            modelBuilder.Entity("BOMA.WTR.Domain.AggregateModels.Entities.WorkingTimeRecordAggregatedHistory", b =>
                {
                    b.HasOne("BOMA.WTR.Domain.AggregateModels.Employee", null)
                        .WithMany("WorkingTimeRecordAggregatedHistories")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("BOMA.WTR.Domain.AggregateModels.Entities.EmployeeSalaryAggregatedHistory", "SalaryInformation", b1 =>
                        {
                            b1.Property<int>("WorkingTimeRecordAggregatedHistoryId")
                                .HasColumnType("int");

                            b1.Property<decimal>("Base100PercentageSalary")
                                .HasColumnType("decimal(10,2)");

                            b1.Property<decimal>("Base50PercentageSalary")
                                .HasColumnType("decimal(10,2)");

                            b1.Property<decimal>("BaseSalary")
                                .HasColumnType("decimal(10,2)");

                            b1.Property<decimal>("BaseSaturdaySalary")
                                .HasColumnType("decimal(10,2)");

                            b1.Property<decimal>("BonusBase100PercentageSalary")
                                .HasColumnType("decimal(10,2)");

                            b1.Property<decimal>("BonusBase50PercentageSalary")
                                .HasColumnType("decimal(10,2)");

                            b1.Property<decimal>("BonusBaseSalary")
                                .HasColumnType("decimal(10,2)");

                            b1.Property<decimal>("BonusBaseSaturdaySalary")
                                .HasColumnType("decimal(10,2)");

                            b1.Property<decimal>("BonusSumSalary")
                                .HasColumnType("decimal(10,2)");

                            b1.Property<decimal>("GrossBase100PercentageSalary")
                                .HasColumnType("decimal(10,2)");

                            b1.Property<decimal>("GrossBase50PercentageSalary")
                                .HasColumnType("decimal(10,2)");

                            b1.Property<decimal>("GrossBaseSalary")
                                .HasColumnType("decimal(10,2)");

                            b1.Property<decimal>("GrossBaseSaturdaySalary")
                                .HasColumnType("decimal(10,2)");

                            b1.Property<decimal>("GrossSumBase100PercentageSalary")
                                .HasColumnType("decimal(10,2)");

                            b1.Property<decimal>("GrossSumBase50PercentageSalary")
                                .HasColumnType("decimal(10,2)");

                            b1.Property<decimal>("GrossSumBaseSalary")
                                .HasColumnType("decimal(10,2)");

                            b1.Property<decimal>("GrossSumBaseSaturdaySalary")
                                .HasColumnType("decimal(10,2)");

                            b1.Property<decimal>("NightBaseSalary")
                                .HasColumnType("decimal(10,2)");

                            b1.HasKey("WorkingTimeRecordAggregatedHistoryId");

                            b1.ToTable("WorkingTimeRecordAggregatedHistories");

                            b1.WithOwner()
                                .HasForeignKey("WorkingTimeRecordAggregatedHistoryId");
                        });

                    b.Navigation("SalaryInformation")
                        .IsRequired();
                });

            modelBuilder.Entity("BOMA.WTR.Domain.AggregateModels.Employee", b =>
                {
                    b.Navigation("WorkingTimeRecordAggregatedHistories");

                    b.Navigation("WorkingTimeRecords");
                });
#pragma warning restore 612, 618
        }
    }
}
