using BOMA.WTR.Application.Abstractions.Messaging;

namespace BOMA.WTR.Application.UseCases.Employees.Commands.EditWorkingTimeRecordsDetailsData;

public record EditWorkingTimeRecordsDetailsDataCommand(
    int EmployeeId,
    int Year, 
    int Month,
    double? Day1,
    double? Day2,
    double? Day3,
    double? Day4,
    double? Day5,
    double? Day6,
    double? Day7,
    double? Day8,
    double? Day9,
    double? Day10,
    double? Day11,
    double? Day12,
    double? Day13,
    double? Day14,
    double? Day15,
    double? Day16,
    double? Day17,
    double? Day18,
    double? Day19,
    double? Day20,
    double? Day21,
    double? Day22,
    double? Day23,
    double? Day24,
    double? Day25,
    double? Day26,
    double? Day27,
    double? Day28,
    double? Day29,
    double? Day30,
    double? Day31) : ICommand;